version: "3.9"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_demo
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=testkey
      - AWS_SECRET_ACCESS_KEY=testsecret
    ports:
      - "4566:4566"
    volumes:
      - "./my_localstack_init:/etc/localstack/init/ready.d"
